import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Cairo } from "next/font/google";
import { Montserrat } from "next/font/google";
import AnimationProvider from "./components/provider/animation-provider";

import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-cairo",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-montserrat",
});

const metadata: Metadata = {
  title: "Tayraan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html
      // lang='en'
      className={`${cairo.variable} ${montserrat.variable}`}
    >
      <Script src="/langs/lang-config.js" strategy="beforeInteractive" />
      <Script src="/langs/translation.js" strategy="beforeInteractive" />
      <Script src="//translate.google.com/translate_a/element.js?cb=TranslateInit" strategy="afterInteractive" />

      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={"anonymous"}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>

        <AnimationProvider>

          {/* <GoogleTranslate /> */}
          {children}
        </AnimationProvider>
      </body>
    </html>
  );
}
